# Generated by Django 3.2.13 on 2022-05-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='store',
            old_name='adrress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.ManyToManyField(to='store.Category'),
        ),
    ]
