# Generated by Django 3.2.13 on 2022-05-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220514_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='img_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
