# Generated by Django 3.2.13 on 2022-05-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='distance',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
