# Generated by Django 3.2.13 on 2022-05-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220514_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='store',
            name='distance_m',
        ),
        migrations.RemoveField(
            model_name='store',
            name='x',
        ),
        migrations.RemoveField(
            model_name='store',
            name='y',
        ),
        migrations.AddField(
            model_name='store',
            name='distance',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
